### PR TITLE
Add Stremio IPTV by dexter21767

### PR DESCRIPTION
**Pull request by LITUATUI**
This is currently working, unlike the Custom M3U Playlist addon.

### CODE REVIEW

**Comment by Sidirfahem38** [comment]
Hi

**Comment by Sidirfahem38** [comment]
Sli from my

**Comment by danamag** [comment]
@LITUATUI hi, we have changed this project to be completely community driven, check out the new docs here: https://github.com/danamag/stremio-addons-list/blob/main/README-community.md

**Comment by Sidirfahem38** [comment]
Yas

**Pull request closed without merging**
